// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/admin.tsx";
import * as $1 from "./routes/api/live-seats.ts";
import * as $2 from "./routes/api/order.ts";
import * as $3 from "./routes/api/scan.ts";
import * as $4 from "./routes/index.tsx";
import * as $5 from "./routes/oauth.tsx";
import * as $6 from "./routes/scan.tsx";
import * as $7 from "./routes/success.tsx";
import * as $8 from "./routes/ui.tsx";
import * as $$0 from "./islands/QRScanner.tsx";
import * as $$1 from "./islands/Seats.tsx";

const manifest = {
  routes: {
    "./routes/admin.tsx": $0,
    "./routes/api/live-seats.ts": $1,
    "./routes/api/order.ts": $2,
    "./routes/api/scan.ts": $3,
    "./routes/index.tsx": $4,
    "./routes/oauth.tsx": $5,
    "./routes/scan.tsx": $6,
    "./routes/success.tsx": $7,
    "./routes/ui.tsx": $8,
  },
  islands: {
    "./islands/QRScanner.tsx": $$0,
    "./islands/Seats.tsx": $$1,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
